### ISSUE TITLE
Fixing the package

### ISSUE THREAD

**Issue by Sm03leBr00t** [orbitdb/example-orbitdb-todomvc#4]
Hey I just want to fix some bugs to at least make this work again :)

smile and :wave:

**Comment by Sm03leBr00t** [comment]
#5

**Comment by Sm03leBr00t** [comment]
Still there is missing code for the URL copy and paste to share the ToDo list and I have no idea how to implement that :/ but it works at least now. I would advise the **fix** of the **Live Demo** as well

**Comment by Sm03leBr00t** [comment]
URL sharing works now! #5 can be pulled in :)

**Comment by shamb0t** [comment]
:wave: Thanks @Sm03leBr00t! Closed by #5
